name: artifact
description: Data Modeling for the local madman
version: 1.0.23
repository: https://github.com/ArcaneArts/artifact
library: true
environment:
  sdk: ^3.7.0
dependencies:
  fast_log: ">=1.0.7 <2.0.0"
  toxic: ">=1.3.0 <2.0.0"
  yaml_edit: ">=2.2.0 <3.0.0"
  yaml: ">=3.1.0 <4.0.0"
  toml: ">=0.16.0 <1.0.0"
  xml: ">=6.0.0 <7.0.0"
  bson: ">=5.0.7 <6.0.0"
  toonx: ">=1.2.0 <2.0.0"
  json_compress: ">=1.0.9 <2.0.0"
  threshold: ">=1.0.5 <2.0.0"
