name: artifact_gen
description: Data Modeling generator for the local madman
version: 1.2.1
repository: https://github.com/ArcaneArts/artifact
library: true
environment:
  sdk: ^3.7.0
dependencies:
  artifact: ">=1.0.23 <2.0.0"
  build: ">=4.0.0 <5.0.0"
  source_gen: ">=4.0.0 <5.0.0"
  analyzer: ">=8.0.0 <10.0.0"
  fast_log: ">=1.0.7 <2.0.0"
  glob: ">=2.1.3 <3.0.0"
  toxic: ">=1.3.0 <2.0.0"
  code_builder: ">=4.10.1 <5.0.0"
dev_dependencies:
  build_runner: ^2.10.0
